language: node_js
node_js:
  - stable
  - 'lts/*'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn reset
script:
  - yarn lint
  - yarn test
